"use client";
import Link from "next/link";
import { CheckCircle2, Copy, Coffee } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { Suspense } from "react";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
export default function SuccessPage() { return <Suspense fallback={<div className="min-h-screen bg-[#0b0908]" />}><SuccessContent /></Suspense>; }
function SuccessContent() { const search = useSearchParams(); const orderId = search.get("orderId") || "SC-RESERVE"; return <><Header /><main className="page-shell"><div className="container-luxury flex min-h-[68vh] items-center justify-center py-14"><section className="panel relative w-full max-w-2xl overflow-hidden rounded-2xl p-8 text-center md:p-14"><div className="absolute left-1/2 top-0 h-32 w-96 -translate-x-1/2 rounded-full bg-[#c8a261]/10 blur-3xl" /><div className="relative"><CheckCircle2 className="mx-auto size-14 text-[#e9c07c]" strokeWidth={1.4} /><p className="mt-6 text-[10px] font-bold tracking-[.25em] text-[#c8a261]">SAMSONS PRIVATE RESERVE</p><h1 className="serif mt-3 text-5xl">Order Placed</h1><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-muted">Thank you. Our staff will review your order and prepare it with care.</p><div className="mx-auto mt-8 flex max-w-sm items-center justify-between rounded-xl border border-[#c8a261]/30 bg-[#0b0908] p-4 text-left"><div><span className="text-[10px] font-bold tracking-widest text-muted">ORDER ID</span><p className="serif mt-1 text-lg text-[#e9c07c]">{orderId}</p></div><button aria-label="Copy order ID" onClick={() => navigator.clipboard?.writeText(orderId)} className="rounded-full p-3 text-[#e9c07c] hover:bg-[#261e1a]"><Copy size={17} /></button></div><div className="mx-auto mt-8 max-w-sm border-y border-[#3d312a] py-6 text-left"><div className="flex gap-3"><Coffee className="shrink-0 text-[#c8a261]" size={20} /><div><p className="font-semibold text-[#faf6f0]">Order confirmed</p><p className="mt-1 text-sm leading-6 text-muted">Keep this order ID handy when collecting your order.</p></div></div></div><Link href="/" className="mt-9 inline-flex items-center rounded-xl bg-[#c8a261] px-6 py-4 text-xs font-bold tracking-[.12em] text-[#241a00] hover:bg-[#e5c158]">BACK TO MENU</Link></div></section></div></main><Footer /></>; }
